version: '3'
services:
  postgres:
    container_name: share-docs-postgres
    image: postgres:latest
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    container_name: share-docs-pgadmin
    image: dpage/pgadmin4
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@sharedocs.io}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin4}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE:-True}
    volumes:
      - pgadmin:/root/.pgadmin
  redis:
    container_name: share-docs-redis
    image: redis:alpine
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis-data:/var/lib/redis/data
      - redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
  rabbitmq:
    container_name: share-docs-rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      # The standard AMQP protocol port
      - '${RABBITMQ_AMQP_PORT:-5672}:5672'
      # HTTP management UI
      - '${RABBITMQ_HTTP_PORT:-15672}:15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-root}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-root}
volumes:
  db-data:
  pgadmin:
  redis-data:
  redis.conf:
  rabbitmq-data:
  rabbitmq-log:
